#MOSTRAR TODOS LOS REGISTROS / FILAS DE UNA TABLA

SELECT email, nombre, apellidos FROM usuarios;  


#MOSTRAR TODOS LOS CAMPOS

SELECT * FROM usuarios;


#OPERADORES ARITMÉTICOS

SELECT email, (7 + 7) AS 'OPERACION' FROM usuarios;

SELECT ID, email, (7 + 7) AS 'OPERACION' FROM usuarios ORDER BY ID; 


#FUNCIONES MATEMÁTICAS

SELECT CEIL (7.7) AS 'OPERACION' FROM usuarios;