#VISUALIZAR LOS APELLIDOS DE LOS VENDEDORES, SU FECHA Y SU NÚMERO DE GRUPO ORDENADO POR FECHA DESCENDENTE Y MOSTRAR LOS 4 ÚTILMOS;

SELECT apellidos, fecha, grupo_id FROM vendedores ORDER BY fecha DESC LIMIT 4;