#SACAR LOS VENDEDORES CON SU RESPECTIVO NOMBRE Y APELLIDO JUNTO CON LOS DÍAS QUE LLEVAN LABORANDO EN EL CONCESIONARIO

SELECT nombre, DATEDIFF(CURDATE(), fecha_alta) AS 'Dias de labor' FROM vendedores;